graph_path: ../data/BJ.txt
coordinates_path: ../data/BJ_NodeIDLonLat.txt
queries_path: ../data/BJ_Synthetic_query_sets/Hop10Rep1-0.txt

alpha: 0.15
beta: 4.0
max_time: 1000000
min_bpr_capacity: 5

max_iterations: 10
enable_timing_log: false
baseline_fraction_to_reroute: 0.30
baseline_random_seed: 0
lambda: 0.45
gamma: 0.5
impact_weight: 0.15
theta_percentile: 0.90
min_slot_width: 600
svp_k: 3
svp_theta: 0.80
