graph_path: /Users/xyh/Desktop/GRO-Pro/data/MH.txt
coordinates_path: /Users/xyh/Desktop/GRO-Pro/data/MH_NodeIDLonLat.txt
queries_path: /Users/xyh/Desktop/GRO-Pro/data/MH_Synthetic_query_sets/Hop10Rep4-0.txt
alpha: 0.15
beta: 4.0
max_time: 3600
max_iterations: 10
enable_timing_log: true
lambda: 0.45
gamma: 0.5
impact_weight: 0.15
theta_percentile: 0.90
min_slot_width: 600
